//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFMDIForm.JKHModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accruals_no_benefits
    {
        public long ID { get; set; }
        public double Number { get; set; }
        public System.DateTime Date { get; set; }
        public long Flat_ID { get; set; }
        public int Service_ID { get; set; }
    }
}
