//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFMDIForm.JKHModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JKHModelContainer : DbContext
    {
        public JKHModelContainer()
            : base("name=JKHModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Дом> ДомSet { get; set; }
        public virtual DbSet<Квартира> КвартираSet { get; set; }
        public virtual DbSet<Счетчик> СчетчикSet { get; set; }
        public virtual DbSet<Жилец> ЖилецSet { get; set; }
        public virtual DbSet<Услуга> УслугаSet { get; set; }
        public virtual DbSet<Соц_норма> Соц_нормаSet { get; set; }
        public virtual DbSet<Льгота> ЛьготаSet { get; set; }
        public virtual DbSet<Показания_квартир> Показания_квартирSet { get; set; }
        public virtual DbSet<Календарь> КалендарьSet { get; set; }
        public virtual DbSet<Показания_ОДУ> Показания_ОДУSet { get; set; }
    }
}
