//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFMDIForm.JKHModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model1Container : DbContext
    {
        public Model1Container()
            : base("name=Model1Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Accruals> Accruals { get; set; }
        public virtual DbSet<Accruals_no_benefits> Accruals_no_benefits { get; set; }
        public virtual DbSet<Льготы> Benefits { get; set; }
        public virtual DbSet<Счетчики> Counter_Data { get; set; }
        public virtual DbSet<Expense> Expense { get; set; }
        public virtual DbSet<Квартира> Flat { get; set; }
        public virtual DbSet<Дом> House { get; set; }
        public virtual DbSet<Жильцы> Occupant { get; set; }
        public virtual DbSet<Overall_accruals> Overall_accruals { get; set; }
        public virtual DbSet<Услуга> Services { get; set; }
        public virtual DbSet<Соц_норма> Social_minimum { get; set; }
    }
}
