//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFMDIForm.JKHModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Дом
    {
        public Дом()
        {
            this.Квартира = new HashSet<Квартира>();
            this.Показания_ОДУ = new HashSet<Показания_ОДУ>();
        }
    
        public int Id { get; set; }
        public string Адрес { get; set; }
        public decimal Площадь { get; set; }
    
        public virtual ICollection<Квартира> Квартира { get; set; }
        public virtual ICollection<Показания_ОДУ> Показания_ОДУ { get; set; }
    }
}
