//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFMDIForm.JKHModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Жильцы
    {
        public Жильцы()
        {
            this.Льготы = new HashSet<Льготы>();
        }
    
        public long Паспорт { get; set; }
        public string ФИО { get; set; }
    
        public virtual ICollection<Льготы> Льготы { get; set; }
    }
}
