//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFMDIForm.JKHModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Жилец
    {
        public Жилец()
        {
            this.Льгота = new HashSet<Льгота>();
        }
    
        public int Id { get; set; }
        public string ФИО { get; set; }
        public string Номер_паспорта { get; set; }
    
        public virtual Квартира Квартира { get; set; }
        public virtual ICollection<Льгота> Льгота { get; set; }
    }
}
