//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFMDIForm.JKHModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Календарь
    {
        public Календарь()
        {
            this.Показания_квартир = new HashSet<Показания_квартир>();
            this.Показания_ОДУ = new HashSet<Показания_ОДУ>();
        }
    
        public int Id { get; set; }
        public string Месяц { get; set; }
        public string Год { get; set; }
    
        public virtual ICollection<Показания_квартир> Показания_квартир { get; set; }
        public virtual ICollection<Показания_ОДУ> Показания_ОДУ { get; set; }
    }
}
