//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFMDIForm.JKHModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Квартира
    {
        public Квартира()
        {
            this.Счетчики = new HashSet<Счетчики>();
        }
    
        public long Номер { get; set; }
        public byte[] Water_Counters { get; set; }
        public double Площадь_квартиры { get; set; }
    
        public virtual ICollection<Счетчики> Счетчики { get; set; }
        public virtual Дом Дом { get; set; }
    }
}
