//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFMDIForm.JKHModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Льгота
    {
        public Льгота()
        {
            this.Жилец = new HashSet<Жилец>();
        }
    
        public int Id { get; set; }
        public string Имя_льготы { get; set; }
        public decimal Значение_льготы { get; set; }
        public bool Общая { get; set; }
    
        public virtual ICollection<Жилец> Жилец { get; set; }
    }
}
