//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFMDIForm.JKHModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Услуга
    {
        public Услуга()
        {
            this.Счетчик = new HashSet<Счетчик>();
            this.Соц_норма = new HashSet<Соц_норма>();
        }
    
        public int Id { get; set; }
        public string Вид_услуги { get; set; }
        public decimal Тариф { get; set; }
        public bool ГВС { get; set; }
        public bool Отопление { get; set; }
        public bool Водоотведение { get; set; }
        public bool Содерж_дома { get; set; }
        public string ХВС { get; set; }
    
        public virtual ICollection<Счетчик> Счетчик { get; set; }
        public virtual ICollection<Соц_норма> Соц_норма { get; set; }
    }
}
