//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFMDIForm.JKHModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Услуга
    {
        public Услуга()
        {
            this.Счетчики = new HashSet<Счетчики>();
            this.Соц_норма = new HashSet<Соц_норма>();
        }
    
        public int ID { get; set; }
        public string Вид_услуги { get; set; }
        public decimal Тариф { get; set; }
        public byte[] ХВС_ГВС { get; set; }
        public byte[] Отопление { get; set; }
        public byte[] Водоотведение { get; set; }
        public byte[] Содерж_дома { get; set; }
    
        public virtual ICollection<Счетчики> Счетчики { get; set; }
        public virtual ICollection<Соц_норма> Соц_норма { get; set; }
    }
}
