//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFMDIForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Услуги
    {
        public Услуги()
        {
            this.Показания = new HashSet<Показания>();
        }
    
        public int Id { get; set; }
    
        public virtual ICollection<Показания> Показания { get; set; }
    }
}
